#=================================================
# State Conditions
#=================================================
State_Conditions:
    Temperature: [298] #Temperature in K, can be given as a list like [T1,T2,T3]
    Pressure: [1] #Pressure in Bar, can be given as a list like [T1,T2,T3]
    Replicas: 1   # Number of replicas to run. e.g. Replicas: 5 produces replica_1 through replica_5.
   

#=================================================
# Molecule Information
#=================================================
Molecule_Information:  
    System_Title: Ethanol #What name are you using for your system (please keep this the same as the folder you have generated for your molecule)
    Gas_Dip: 1.690 # Please give us the gas phase of the molecule you are investigating Not sure where to put this when mixture
    Di_Const: 24.852 # Please give us the experimental dielectric constant of the molecule you are investigating Not sure where to put this when mixture
    Ref_Ind: 1.361 # Please give us the refractive index of the molecule you are investigating Not sure where to put this when mixture
    sol_keyword: Ethanol #These can be obtained on the SCRF Website # Will need some guidance on what to do when this isn't available? Not sure where to put this when mixture
    
    density: 0.7849 # Experimental Density in g/cm^3 
    mol_mass: 46.068 # Molar Mass of Molecule g/mol
    
    AA_Surround: No  # YES or No #If you want to use AA to describe your MM layer say yes, if no we will use UA.
    Solvent_Smiles: OCC # Add a smile string here and we will use RD Kit to build your molecule. #Change to null to use your own gro_file
    Mixture: No                # if No, Solute_Smiles is ignored
    Solute_Smiles: null        # only used if Mixture: Yes
#=================================================
# Advanced settings - Do not modify if unsure
#=================================================
Advanced_Settings:         
    configuration:
        box_length_nm: 6.2        # Length of the simulation box used when no gro is provided or when building a gro
        cluster_radius_nm: 2.8    # Radius of the cluster used in dipole calculations
                                  # Minimum recommended value is ~2.5 nm
    sampling:
        n_configurations: 200     # Number of configurations extracted from MD
                                  # Extracted every 20 ps after 1 ns
                                  # Minimum ~150 configurations required for convergence
                                  # May need option to include configurations outside fitting step
    electrostatics:
        charge_scaling:
            qr1: 1.0              # Scaling factor for charge set 1
            qr2: 1.35             # Scaling factor for charge set 2
            qr3: 1.7              # Scaling factor for charge set 3    
            
    electronic_structure:
        v0:
            method: b3lyp
            basis: 6-31+G(d,p)
        v1:
            method: blyp
            basis: aug-cc-pvtz
    filtering:
         iqr_k: 2.0                  # IQR multiplier (you already use 2.0)
         max_iqr_passes: 2           # hard cap on how many IQR passes
         min_pass_outliers: 3        # early termination: stop if a pass finds fewer than this
         min_kept_configs: 150       # convergence floor
#=================================================
# Software Settings - Give us your software location and make adjustments if and only if you know what your doing.
#=================================================
Software:
    GROMACS:
        ntmpi: 1
        ntomp: 8
        pin: "on"
        pinoffset: 0
    Gaussian:
        g09root_override: /home/zoe/Software/Gaussian/g09_pgi         # null = auto-detect; set to Gaussian install root to override
        scratch_dir: /home/zoe/Research/Gaussian/scratch # where Gaussian writes temporary files
        max_jobs: 6 # how many parallel Gaussian jobs (depends on machine)
        nproc: 8
        mem: 5GB
