#=================================================
# State Conditions
#=================================================
State_Conditions:
    Temperature: [298] #Temperature in K, can be given as a list like [T1,T2,T3]
    Pressure: [1] #Pressure in Bar, can be given as a list like [T1,T2,T3]
    Replicas: 5   # Number of replicas to run. e.g. Replicas: 5 produces replica_1 through replica_5.
   

#=================================================
# Molecule Information
#=================================================
Molecule_Information:  
    System_Title: Ethanol #What name are you using for your system (please keep this the same as the folder you have generated for your molecule)
    Gas_Dip: 1.690 # Please give us the gas phase of the molecule you are investigating Not sure where to put this when mixture
    Di_Const: 24.852 # Please give us the experimental dielectric constant of the molecule you are investigating Not sure where to put this when mixture
    Ref_Ind: 1.361 # Please give us the refractive index of the molecule you are investigating Not sure where to put this when mixture
    sol_keyword: Ethanol #These can be obtained on the SCRF Website # Will need some guidance on what to do when this isn't available? Not sure where to put this when mixture
    
    density: 0.7849 # Experimental Density in g/cm^3 
    mol_mass: 46.068 # Molar Mass of Molecule g/mol
    
    AA_Surround: Yes  # YES or No #If you want to use AA to describe your MM layer say yes, if no we will use UA.
    Solvent_Smile: CCO # Add a smile string here and we will use RD Kit to build your molecule. #Change to null to use your own gro_file
    Solute_Smile: null  #Leave null unless you intend to study a mixture # Add a smile string here and we will use RD Kit to build your molecule. #Change to No to use your own gro_file
#=================================================
# Software Settings #Will need to format to be more user variable or do something in the script for it to search and locate, realistically should be a set and done.
#=================================================
Software:
    Gaussian:
        GAUSS_SCRDIR: /home/zoe/Research/Gaussian/scratch # optional, defaults to here
        max_jobs: 6                       # how many parallel Gaussian jobs
    # GROMACS auto-detected from $PATH; specify here only if needed
    GROMACS_Override: /home/zoe/Software/gromacs-2024.2/bin/GMXRC.bash               # optional override for non-standard installs
    Gaussian_Override: /home/zoe/Software/Gaussian/g09_pgi            # optional override for non-standard installs
#=================================================
# Advanced settings - Do not modify if unsure
#=================================================
Advanced_Settings:         
    configuration:
        box_length_nm: 6.2        # Length of the simulation box used when no gro is provided or when building a gro
        cluster_radius_nm: 2.8    # Radius of the cluster used in dipole calculations
                                  # Minimum recommended value is ~2.5 nm
    sampling:
        n_configurations: 200     # Number of configurations extracted from MD
                                  # Extracted every 20 ps after 1 ns
                                  # Minimum ~150 configurations required for convergence
                                  # May need option to include configurations outside fitting step
    electrostatics:
        charge_scaling:
            qr1: 0.8              # Scaling factor for charge set 1
            qr2: 1.1             # Scaling factor for charge set 2
            qr3: 1.5              # Scaling factor for charge set 3    
